### ISSUE TITLE
Issue creating Search Index - 'Error making network request'

### ISSUE THREAD

**Issue by joe-restore** [couchbase-examples/rag-demo#10] opened 2024-04-30 10:26 UTC
I am getting 'Error making network request' when trying to create the search index for this demo. I have allowed my IP in the db settings and have copied the index.json file from https://developer.couchbase.com/tutorial-python-langchain-pdf-chat.

Any ideas? It is preventing me from carrying on with this.

Many thanks,
Joe
[index.json](https://github.com/couchbase-examples/rag-demo/files/15161934/index.json)
![error_screenshot](https://github.com/couchbase-examples/rag-demo/assets/132987487/fa16eea8-e993-4441-89d2-f32cd57fdd33)

**Comment by nithishr** [comment] 2024-04-30 18:57
Hi @joe-restore, 

That is interesting. I think that it has something to do with the Couchbase cluster. I have only seen this behavior previously on a cluster that does not support Vector Search (pre 7.6). 

Would it be possible for you to look at the network request in the browser network tab & share the `Vnd-Cloud-Couchbase-Com-Request-Id` from the headers of the request to create the search index that fails?

Alternatively, you can open a support request on Capella & support would be able to sort you out.

**Comment by nithishr** [comment] 2024-05-10 14:59
Closing this issue as the issue is related to an unsupported Couchbase Server. 
Have added a note to use Couchbase 7.6 or higher on the repo.

**Closed by nithishr** 2024-05-10 14:59 UTC
